name: Update China IPv6 List

on:
  schedule:
    - cron: '0 12 * * *'  # 每天UTC时间12:00运行
  workflow_dispatch:       # 允许手动触发

permissions:
  contents: write

jobs:
  generate-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Generate IPv4 list
        run: python generate_ipv4_list.py
        
      - name: Generate IPv6 list
        run: python generate_ipv6_list.py
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "GitHub Actions"
          git add china-ipv4.rsc china-ipv6.rsc
          git commit -am "Update China IP lists - $(date +'%Y-%m-%d')"
          git push
