name: Update CN IPv6 List
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create directories
        run: mkdir -p data outputs
      - name: Install dependencies
        run: pip install requests
      - name: Run scripts
        run: |
          python scripts/fetch_cnipv6.py
          python scripts/convert_to_ros.py
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add outputs/cn_ipv6.rsc
          git commit -m "Auto-update CN IPv6 list $(date +'%Y-%m-%d')"
          git push
